"""
Agent API Endpoints
POST /api/v1/agent/chat    — SSE stream for text prompt
POST /api/v1/agent/upload  — SSE stream for document upload

These are the central endpoints — they invoke the LangGraph agent
and stream events back to the frontend as Server-Sent Events.
"""
import json
import logging
import uuid
from typing import AsyncGenerator

from fastapi import APIRouter, Depends, UploadFile, File, Form, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.core.config import settings
from app.schemas.agent import ChatRequest, SaveComplaintRequest, SaveComplaintResponse
from app.schemas.complaint import ComplaintData, ComplaintCreate, ComplaintUpdate
from app.schemas.risk_assessment import RiskAssessmentData
from app.agent.graph import complaint_graph
from app.agent.state import AgentState
from app.crud.complaint import (
    create_complaint,
    update_complaint,
    get_complaint,
    get_complaint_by_thread,
    get_all_complaints_for_dedup,
)
from app.crud.risk_assessment import upsert_risk_assessment
from app.services.document_parser import parse_document
from app.services.duplicate_detector import check_for_duplicates
from langchain_core.messages import HumanMessage, AIMessage

logger = logging.getLogger(__name__)
router = APIRouter()


def _sse_line(event_type: str, data: dict) -> str:
    """Format a single SSE event line."""
    return f"data: {json.dumps({'type': event_type, **data})}\n\n"


async def _run_graph_stream(
    initial_state: AgentState,
    db: AsyncSession,
) -> AsyncGenerator[str, None]:
    """
    Core streaming generator.
    Uses ainvoke (single call) for reliability, emits SSE events at key steps.

    Event sequence:
    1. thinking        — before graph runs
    2. tool_call       — which intent was detected
    3. complaint_update — form data after extraction
    4. risk_update     — risk assessment data
    5. warning         — duplicate detection
    6. message         — final AI text
    7. done            — stream complete
    """
    try:
        intent = initial_state.get("intent")
        if initial_state.get("document_text"):
            intent = "document"

        # Emit early "thinking" before invoking graph
        thinking_labels = {
            "log": "Extracting complaint details...",
            "edit": "Applying updates and checking form...",
            "document": "Extracting from document...",
            "query": "Thinking...",
        }
        yield _sse_line("thinking", {"content": thinking_labels.get(intent or "log", "Processing...")})

        tool_labels = {
            "log": "log_complaint",
            "edit": "edit_complaint",
            "document": "document_extract",
        }
        if intent in tool_labels:
            yield _sse_line("tool_call", {"tool": tool_labels[intent]})

        # ── Single graph invocation ───────────────────────────────────────────
        final_state = await complaint_graph.ainvoke(initial_state)

        complaint_data = final_state.get("complaint_data")
        risk_data = final_state.get("risk_assessment")
        dup = None

        # Sync severity & priority to complaint_data if generated by risk assessment
        if risk_data and complaint_data:
            if risk_data.get("severity_level"):
                complaint_data["initial_severity"] = risk_data["severity_level"]
            if not complaint_data.get("priority"):
                complaint_data["priority"] = (
                    "Immediate" if risk_data.get("severity_level") == "Critical"
                    else "High" if risk_data.get("severity_level") == "Major"
                    else "Medium"
                )

        # ── Emit form data to frontend ────────────────────────────────────────
        if complaint_data:
            yield _sse_line("complaint_update", {"data": complaint_data})
            yield _sse_line("thinking", {"content": "Generating risk assessment..."})
            yield _sse_line("tool_call", {"tool": "risk_assessment"})

        # ── Emit risk assessment to frontend ──────────────────────────────────
        if risk_data:
            yield _sse_line("risk_update", {"data": risk_data})
        elif complaint_data and final_state.get("intent") in ("log", "edit", "document"):
            yield _sse_line("warning", {
                "content": (
                    "⚠️ I couldn't generate a risk assessment for this complaint. "
                    "The form was populated, but please review it manually before saving."
                ),
                "data": None,
            })

        # ── Duplicate detection (bonus) ────────────────────────────────────────
        if complaint_data:
            existing = await get_all_complaints_for_dedup(
                db,
                new_complaint=complaint_data,
                exclude_complaint_id=(
                    initial_state.get("complaint_id")
                    or final_state.get("complaint_id")
                ),
                date_tolerance_days=settings.DATE_TOLERANCE_DAYS,
            )
            dup = check_for_duplicates(
                new_complaint=complaint_data,
                existing_complaints=existing,
                date_tolerance_days=settings.DATE_TOLERANCE_DAYS,
            )
            if dup:
                yield _sse_line("warning", {
                    "content": f"⚠️ Possible duplicate of **{dup['complaint_number']}** "
                               f"(same product, issue, source, date). Please review before saving.",
                    "data": dup,
                })

        # ── Final AI message ─────────────────────────────────────────────────
        messages = final_state.get("messages", [])
        last_ai_msg = next(
            (m.content for m in reversed(messages) if hasattr(m, "type") and m.type == "ai"),
            None
        )
        if last_ai_msg:
            if dup:
                last_ai_msg = (
                    f"⚠️ **Possible duplicate detected**: this matches existing complaint "
                    f"**{dup['complaint_number']}** (same product, issue, source, date). "
                    f"Please review before saving.\n\n{last_ai_msg}"
                )
            yield _sse_line("message", {"content": last_ai_msg})

        yield _sse_line("done", {})

    except Exception as e:
        logger.exception(f"Graph stream error: {e}")
        yield _sse_line("error", {"content": f"An error occurred: {str(e)}"})
        yield _sse_line("done", {})


@router.post("/chat")
async def chat_with_agent(
    request: ChatRequest,
    db: AsyncSession = Depends(get_db),
):
    """
    SSE endpoint for text-based complaint intake.
    Accepts natural language prompt, accumulates multi-turn form state and history.
    """
    # 1. Recover existing complaint data for this thread from DB
    existing_db = await get_complaint_by_thread(db, request.thread_id)
    accumulated_complaint: dict = {}

    if existing_db:
        # Whitelist to ComplaintData fields — never carry DB-only columns
        # (status, complaint_number, intake_source, timestamps) into agent state.
        allowed = ComplaintData.model_fields
        for col in existing_db.__table__.columns.keys():
            if col not in allowed:
                continue
            val = getattr(existing_db, col, None)
            if val is not None:
                accumulated_complaint[col] = str(val)

    # 2. Overlay any frontend active form fields from request.current_complaint
    if request.current_complaint:
        for k, v in request.current_complaint.items():
            if v is not None and str(v).strip() != "":
                accumulated_complaint[k] = str(v).strip()

    # 3. Build messages list (from history if provided, plus latest user message)
    lang_messages = []
    if request.history:
        for h in request.history:
            if h.role == "user":
                lang_messages.append(HumanMessage(content=h.content))
            else:
                lang_messages.append(AIMessage(content=h.content))
    else:
        lang_messages.append(HumanMessage(content=request.message))

    # Ensure the current message is at the end if not already
    if not lang_messages or lang_messages[-1].content != request.message:
        lang_messages.append(HumanMessage(content=request.message))

    initial_state: AgentState = {
        "messages": lang_messages,
        "intent": None,
        "complaint_data": accumulated_complaint if accumulated_complaint else None,
        "risk_assessment": None,
        "document_text": None,
        "complaint_id": str(existing_db.id) if existing_db else request.complaint_id,
        "thread_id": request.thread_id,
        "error": None,
        "duplicate_warning": None,
    }

    return StreamingResponse(
        _run_graph_stream(initial_state, db),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",    # Disable Nginx buffering for Render
            "Connection": "keep-alive",
        },
    )


@router.post("/upload")
async def upload_document(
    file: UploadFile = File(...),
    thread_id: str = Form(...),
    db: AsyncSession = Depends(get_db),
):
    """
    SSE endpoint for document upload complaint intake.
    Parses file → extracts text → runs document_extract tool → streams events.
    """
    # Validate file size
    max_bytes = settings.MAX_FILE_SIZE_MB * 1024 * 1024
    content = await file.read()

    if len(content) > max_bytes:
        raise HTTPException(
            status_code=413,
            detail=f"File too large. Maximum size: {settings.MAX_FILE_SIZE_MB}MB",
        )

    # Validate extension
    filename = file.filename or "upload"
    ext = "." + filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
    if ext not in settings.ALLOWED_EXTENSIONS:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported format: {ext}. Allowed: {settings.ALLOWED_EXTENSIONS}",
        )

    async def upload_stream() -> AsyncGenerator[str, None]:
        # Immediate progress feedback
        yield _sse_line("progress", {"progress": 10, "content": "Analyzing document content and extracting key details..."})

        try:
            document_text = parse_document(content, filename)
            yield _sse_line("progress", {"progress": 35, "content": "Document parsed successfully. Running AI extraction..."})
        except Exception as e:
            yield _sse_line("error", {"content": f"Could not read document: {str(e)}"})
            yield _sse_line("done", {})
            return

        if not document_text.strip():
            yield _sse_line("error", {"content": "Document appears to be empty or unreadable."})
            yield _sse_line("done", {})
            return

        yield _sse_line("progress", {"progress": 50, "content": "Extracting complaint fields with AI..."})

        initial_state: AgentState = {
            "messages": [HumanMessage(content=f"Extract complaint from uploaded document: {filename}")],
            "intent": "document",  # Pre-classified
            "complaint_data": None,
            "risk_assessment": None,
            "document_text": document_text,
            "complaint_id": None,
            "thread_id": thread_id,
            "error": None,
            "duplicate_warning": None,
        }

        yield _sse_line("progress", {"progress": 65, "content": "Populating complaint form..."})

        async for event in _run_graph_stream(initial_state, db):
            yield event
            # Advance progress to 95% during streaming
            yield _sse_line("progress", {"progress": 95, "content": "Finalizing..."})

        yield _sse_line("progress", {"progress": 100, "content": "Extraction complete!"})

    return StreamingResponse(
        upload_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )


@router.post("/save", response_model=SaveComplaintResponse)
async def save_complaint(
    request: SaveComplaintRequest,
    db: AsyncSession = Depends(get_db),
):
    """
    Explicit save — the only place a complaint is persisted.
    Called when the user clicks "Save Complaint" in the UI.
    Creates a new record on first save (returns complaint number), otherwise
    updates the existing record. Risk assessment is upserted when provided.
    """
    try:
        complaint_schema = ComplaintData(**request.complaint)
    except Exception as e:
        raise HTTPException(status_code=422, detail=f"Invalid complaint data: {e}")

    payload = {
        k: v for k, v in complaint_schema.model_dump(exclude_none=True).items()
        if v not in (None, "")
    }

    existing = None
    if request.complaint_id:
        existing = await get_complaint(db, request.complaint_id)

    if existing:
        update_schema = ComplaintUpdate(**payload)
        saved = await update_complaint(
            db, str(existing.id), update_schema,
            thread_id=request.thread_id, performed_by="manual_save",
        )
        action = "complaint_updated_via_save"
    else:
        create_schema = ComplaintCreate(
            **payload,
            thread_id=request.thread_id,
            intake_source=request.intake_source,
        )
        saved = await create_complaint(
            db, create_schema, thread_id=request.thread_id,
            status="Under Investigation",
        )
        action = "complaint_created_via_save"

    # Persist risk assessment if the AI produced one
    if request.risk_assessment and saved:
        risk_data = {
            k: v for k, v in request.risk_assessment.items()
            if k in RiskAssessmentData.model_fields
            and v is not None and (not isinstance(v, str) or v.strip())
        }
        if risk_data:
            risk_schema = RiskAssessmentData(**risk_data)
            await upsert_risk_assessment(
                db, str(saved.id), risk_schema, thread_id=request.thread_id
            )

    logger.info(
        f"[save] {action} id={saved.id} number={saved.complaint_number} "
        f"thread={request.thread_id} fields={len(payload)}"
    )
    return SaveComplaintResponse(
        id=str(saved.id),
        complaint_number=saved.complaint_number,
        status=saved.status,
    )
